# Generated by Django 5.2 on 2025-04-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_paymentmethod_favoritegarage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='license_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
