# Generated by Django 5.2 on 2025-04-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_alter_user_national_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='owner_name',
            new_name='user',
        ),
    ]
